/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'IdentityRegistry', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IdentityRegistry__factory>
getContractFactory(name: 'IdentityToken', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IdentityToken__factory>

  getContractAt(name: 'IdentityRegistry', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IdentityRegistry>
getContractAt(name: 'IdentityToken', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IdentityToken>

  deployContract(name: 'IdentityRegistry', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IdentityRegistry>
deployContract(name: 'IdentityToken', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IdentityToken>

  deployContract(name: 'IdentityRegistry', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IdentityRegistry>
deployContract(name: 'IdentityToken', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IdentityToken>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  