/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface IdentityRegistryInterface extends Interface {
    getFunction(nameOrSignature: "admin" | "authorizeIssuer" | "authorizedIssuers" | "createOrUpdateProfile" | "credentialCount" | "credentials" | "getProfile" | "issueCredential" | "profiles" | "revokeCredential" | "verifyCredential"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CredentialIssued" | "CredentialRevoked" | "IssuerAuthorized" | "ProfileUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'admin', values?: undefined): string;
encodeFunctionData(functionFragment: 'authorizeIssuer', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'authorizedIssuers', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'createOrUpdateProfile', values: [string, string, string]): string;
encodeFunctionData(functionFragment: 'credentialCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'credentials', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getProfile', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'issueCredential', values: [AddressLike, string, string, BigNumberish]): string;
encodeFunctionData(functionFragment: 'profiles', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeCredential', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'verifyCredential', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'admin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'authorizeIssuer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'authorizedIssuers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createOrUpdateProfile', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'credentialCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'credentials', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getProfile', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'issueCredential', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'profiles', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeCredential', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifyCredential', data: BytesLike): Result;
  }

  
    export namespace CredentialIssuedEvent {
      export type InputTuple = [id: BigNumberish, subject: AddressLike, issuer: AddressLike, credentialType: string];
      export type OutputTuple = [id: bigint, subject: string, issuer: string, credentialType: string];
      export interface OutputObject {id: bigint, subject: string, issuer: string, credentialType: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CredentialRevokedEvent {
      export type InputTuple = [id: BigNumberish, issuer: AddressLike];
      export type OutputTuple = [id: bigint, issuer: string];
      export interface OutputObject {id: bigint, issuer: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace IssuerAuthorizedEvent {
      export type InputTuple = [issuer: AddressLike, status: boolean];
      export type OutputTuple = [issuer: string, status: boolean];
      export interface OutputObject {issuer: string, status: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProfileUpdatedEvent {
      export type InputTuple = [user: AddressLike, name: string, email: string, metadataURI: string];
      export type OutputTuple = [user: string, name: string, email: string, metadataURI: string];
      export interface OutputObject {user: string, name: string, email: string, metadataURI: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface IdentityRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): IdentityRegistry;
    waitForDeployment(): Promise<this>;

    interface: IdentityRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    admin: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    authorizeIssuer: TypedContractMethod<
      [issuer: AddressLike, status: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    authorizedIssuers: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    createOrUpdateProfile: TypedContractMethod<
      [name: string, email: string, metadataURI: string, ],
      [void],
      'nonpayable'
    >
    

    
    credentialCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    credentials: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, string, string, bigint, bigint, boolean, boolean] & {id: bigint, subject: string, issuer: string, credentialType: string, dataHash: string, issueDate: bigint, expiryDate: bigint, isRevoked: boolean, exists: boolean }],
      'view'
    >
    

    
    getProfile: TypedContractMethod<
      [user: AddressLike, ],
      [[string, string, string, bigint, boolean] & {name: string, email: string, metadataURI: string, createdAt: bigint, exists: boolean }],
      'view'
    >
    

    
    issueCredential: TypedContractMethod<
      [subject: AddressLike, credentialType: string, dataHash: string, expiryDate: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    profiles: TypedContractMethod<
      [arg0: AddressLike, ],
      [[string, string, string, bigint, boolean] & {name: string, email: string, metadataURI: string, createdAt: bigint, exists: boolean }],
      'view'
    >
    

    
    revokeCredential: TypedContractMethod<
      [id: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    verifyCredential: TypedContractMethod<
      [id: BigNumberish, ],
      [[boolean, string, string, string, string, bigint, boolean] & {isValid: boolean, subject: string, issuer: string, credentialType: string, dataHash: string, expiryDate: bigint, isRevoked: boolean }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'admin'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'authorizeIssuer'): TypedContractMethod<
      [issuer: AddressLike, status: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'authorizedIssuers'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'createOrUpdateProfile'): TypedContractMethod<
      [name: string, email: string, metadataURI: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'credentialCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'credentials'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, string, string, bigint, bigint, boolean, boolean] & {id: bigint, subject: string, issuer: string, credentialType: string, dataHash: string, issueDate: bigint, expiryDate: bigint, isRevoked: boolean, exists: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'getProfile'): TypedContractMethod<
      [user: AddressLike, ],
      [[string, string, string, bigint, boolean] & {name: string, email: string, metadataURI: string, createdAt: bigint, exists: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'issueCredential'): TypedContractMethod<
      [subject: AddressLike, credentialType: string, dataHash: string, expiryDate: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'profiles'): TypedContractMethod<
      [arg0: AddressLike, ],
      [[string, string, string, bigint, boolean] & {name: string, email: string, metadataURI: string, createdAt: bigint, exists: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'revokeCredential'): TypedContractMethod<
      [id: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'verifyCredential'): TypedContractMethod<
      [id: BigNumberish, ],
      [[boolean, string, string, string, string, bigint, boolean] & {isValid: boolean, subject: string, issuer: string, credentialType: string, dataHash: string, expiryDate: bigint, isRevoked: boolean }],
      'view'
    >;

    getEvent(key: 'CredentialIssued'): TypedContractEvent<CredentialIssuedEvent.InputTuple, CredentialIssuedEvent.OutputTuple, CredentialIssuedEvent.OutputObject>;
getEvent(key: 'CredentialRevoked'): TypedContractEvent<CredentialRevokedEvent.InputTuple, CredentialRevokedEvent.OutputTuple, CredentialRevokedEvent.OutputObject>;
getEvent(key: 'IssuerAuthorized'): TypedContractEvent<IssuerAuthorizedEvent.InputTuple, IssuerAuthorizedEvent.OutputTuple, IssuerAuthorizedEvent.OutputObject>;
getEvent(key: 'ProfileUpdated'): TypedContractEvent<ProfileUpdatedEvent.InputTuple, ProfileUpdatedEvent.OutputTuple, ProfileUpdatedEvent.OutputObject>;

    filters: {
      
      'CredentialIssued(uint256,address,address,string)': TypedContractEvent<CredentialIssuedEvent.InputTuple, CredentialIssuedEvent.OutputTuple, CredentialIssuedEvent.OutputObject>;
      CredentialIssued: TypedContractEvent<CredentialIssuedEvent.InputTuple, CredentialIssuedEvent.OutputTuple, CredentialIssuedEvent.OutputObject>;
    

      'CredentialRevoked(uint256,address)': TypedContractEvent<CredentialRevokedEvent.InputTuple, CredentialRevokedEvent.OutputTuple, CredentialRevokedEvent.OutputObject>;
      CredentialRevoked: TypedContractEvent<CredentialRevokedEvent.InputTuple, CredentialRevokedEvent.OutputTuple, CredentialRevokedEvent.OutputObject>;
    

      'IssuerAuthorized(address,bool)': TypedContractEvent<IssuerAuthorizedEvent.InputTuple, IssuerAuthorizedEvent.OutputTuple, IssuerAuthorizedEvent.OutputObject>;
      IssuerAuthorized: TypedContractEvent<IssuerAuthorizedEvent.InputTuple, IssuerAuthorizedEvent.OutputTuple, IssuerAuthorizedEvent.OutputObject>;
    

      'ProfileUpdated(address,string,string,string)': TypedContractEvent<ProfileUpdatedEvent.InputTuple, ProfileUpdatedEvent.OutputTuple, ProfileUpdatedEvent.OutputObject>;
      ProfileUpdated: TypedContractEvent<ProfileUpdatedEvent.InputTuple, ProfileUpdatedEvent.OutputTuple, ProfileUpdatedEvent.OutputObject>;
    
    };
  }