/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IdentityRegistry } from './IdentityRegistry.js';
export * as factories from './factories/index.js';
export { IdentityRegistry__factory } from './factories/IdentityRegistry__factory.js';