/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IdentityRegistry__factory } from './IdentityRegistry__factory.js';
export { IdentityToken__factory } from './IdentityToken__factory.js';